### ISSUE TITLE
Inline source support?

### ISSUE THREAD

**Issue by vorg** [stackgl/glslify-deps#1]
Would it be possible to match glslify and add support for inline code? This would allow for building UberShaders out of chunks.

``` javascript
depper.add(glslSourceString, { inline: true }, [callback])
```

**Comment by hughsk** [comment]
Right now it's kind of hacky getting inline mode working: https://github.com/stackgl/glslify/blob/2.0.0/index.js#L111-L122

I think I'll add something like this to simplify :)

``` javascript
depper.inline(glslSourceString, { basedir: __dirname }, [callback])
```
